name: On-demand self-hosted AWS EC2 runner for GitHub Actions with windows support
description: GitHub Action for automatic creation and registration AWS EC2 instance as a GitHub Actions self-hosted runner.
author: Volodymyr Machula
branding:
  icon: 'box'
  color: 'orange'
inputs:
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  ec2-os:
    description: >-
      Base OS type of the EC2 image (AMI). The new runner needs to be configured based on OS and architecture:
        - 'windows'
        - 'mac'
    required: false
    default: windows
  ec2-auto-scaling-group-name:
    description: >-
      Name of the group to use for launching instances
    required: false
    default: testdriver_runners
      

outputs:
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used in two cases:
      - to use as the input of 'runs-on' property for the following jobs;
      - to remove the runner from GitHub when it is not needed anymore.
  ec2-instance-id:
    description: >-
      EC2 Instance Id of the created runner.
      The id is used to terminate the EC2 instance when the runner is not needed anymore.
runs:
  using: node16
  main: ./dist/index.js
