name: EC2 GitHub Runner Workflow

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to run on'
        required: true
        default: 'tarun/linux-docker'
        type: string
      mode:
        description: 'Mode (start/stop)'
        required: true
        type: choice
        options:
          - start
          - stop

jobs:
  manage-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Manage EC2 Runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: ${{ github.event.inputs.mode }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ec2-image-id: ${{ github.event.inputs.ec2-image-id }}
          ec2-instance-type: ${{ github.event.inputs.ec2-instance-type }}
          subnet-id: ${{ github.event.inputs.subnet-id }}
          security-group-id: ${{ github.event.inputs.security-group-id }}
          label: ${{ github.event.inputs.label }}
          ec2-instance-id: ${{ github.event.inputs.ec2-instance-id }}
          iam-role-name: ${{ github.event.inputs.iam-role-name }}
          aws-resource-tags: ${{ github.event.inputs.aws-resource-tags }}
          runner-home-dir: ${{ github.event.inputs.runner-home-dir }}
          pre-runner-script: ${{ github.event.inputs.pre-runner-script }}
          use-docker: ${{ github.event.inputs.use-docker }}
          docker-commands: ${{ github.event.inputs.docker-commands }}
